### ISSUE TITLE
Breaks for Roles

### ISSUE THREAD

**Issue by LuckFire** [Snapperito/Settings-Icons#10]
It breaks in the roles tab (only for locked roles tho)
![img](https://cdn.discordapp.com/attachments/755015869914152981/762527404064636938/unknown.png)

and inside of permissions
![img](https://media.discordapp.net/attachments/755015869914152981/762526739515310120/unknown.png)

**Comment by MulverineX** [comment]
second part is fixed, working on first

**Comment by MulverineX** [comment]
fixed
