### ISSUE TITLE
Theme breaks when using DevilBro's DiscordRecolor

### ISSUE THREAD

**Issue by akisblack** [Snapperito/Settings-Icons#16]
## The issue itself

The Settings-Icons theme breaks when using it together with DevilBro's DiscordRecolor. I have tried disabling all my plugins and themes. 

## How to reproduce

1. Have both DiscordRecolor and Settigns-Icons enabled on your modded client.
2. Open the settings menu.

These steps will result in this chaos https://akisblack.github.io/si.png 

I use Powercord, and I only tested the issue there.

**Comment by MulverineX** [comment]
@akisblack I would recommend using [Theme-Source](https://github.com/LuckFire/Theme-Source) instead. It serves the same purpose as Recolor but is generally the better option, and doesn't cause issues like this. If you want that already pre-themed for you [Dark Discord](https://github.com/snappercord/Dark-Discord) uses it

**Comment by akisblack** [comment]
I reported it as an issue because it started happening today, and it wasn't like they weren't compatible.

**Comment by Snapperito** [comment]
after some testing, i can say that this problem most likely comes from devilbros recolor, i can try to fix this strictly from settings icons once me and mulv decide to work on it again, but for now, unfortunately, you will either have to live with this issue, or switch to theme source. as mulv did say there is a theme premade with native powercord support to achieve the look you're searching for. sorry for the inconvenience.

**Comment by MulverineX** [comment]
Closing because we probably will never get around to this. Just use Theme Source, lots of themes depend on it now so it will probably get maintained.
