### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Cellier-Kerrian** [Snapperito/Settings-Icons#21]
Hello,

First of all sorry for my message in English, I am French.
I have a little problem, I can't install your theme / plugin, yet I put it in my file 'C: \ Users \ misterdark \ AppData \ Roaming \ betterdiscord \ themes', using from the GitHub Desktop app, but my Discord doesn't change, even after a reboot.
For information I have Better Discord to install.

![image](https://user-images.githubusercontent.com/69794891/112738226-36dd3b00-8f61-11eb-99f2-a5ad5b5f9981.png)
![image](https://user-images.githubusercontent.com/69794891/112738190-d64dfe00-8f60-11eb-9ca6-576b3222c61b.png)

With that, thank you in advance for your return and have a good day.

**Comment by Snapperito** [comment]
Hey! this theme isnt made for better discord, but it will show compatibility in the near future, for now check out [devilbros settings icons](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Themes/_res/SettingsIcons.css). Also, most of the flashy functionality that powercord gains from this theme, are impossible to replicate on better discord, I can elaborate if necessary

**Comment by Cellier-Kerrian** [comment]
Well, thank you because the link you gave me works perfectly with Better Discord.
![image](https://user-images.githubusercontent.com/69794891/112751191-e3a0d200-8fcc-11eb-871f-f9bd4d2443bf.png)

Thank you very much for your help.
